version: "2.1"

services:
  duspro-api:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ".tmp/:/app/.tmp"
      - "./public/:/app/public"
      - "./data/:/app/data"
    env_file:
      - .env
